### ISSUE TITLE
Missing feature envelopes and geometries after importing CityGML 3.0 data

### ISSUE THREAD

**Issue by bsttsai** [3dcitydb/citydb-tool#29] opened 2024-06-26 16:22 UTC
Hi, I'd like to inquire about an issue encountered when importing CityGML 3.0 test datasets into PostgreSQL.

- Description
I downloaded the TUM CityGML 3.0 Transportation example dataset from this [link](https://github.com/tum-gis/citygml3.0-transportation-examples/tree/master/TUM_transportation_citygmlV3).

I imported the TUM_citygml_V3.gml file using citydb-tool v. 0.7.1-beta, and no errors were seen in the log file. However, upon checking the feature and geometry_data tables, I found that the features' envelopes and geometries were missing—they were both empty.

To troubleshoot, I also tried importing the FZK Haus CityGML 3.0 test dataset from this [link](https://www.citygmlwiki.org/index.php?title=FZK_Haus_CityGML_30). In this case, the feature envelopes and geometries were imported correctly.

- Possible Cause
I suspect the issue may be related to the different closing tags for geometries. The TUM dataset has additional layers of tags (Surface, patches, and PolygonPatch) enclosing the exterior, while the FZK dataset only uses Polygon tags.
excerpt of TUM gml file:
![image](https://github.com/3dcitydb/citydb-tool/assets/42941872/88b7e2e5-544a-47c2-9a7e-c77e5633fd88)

excerpt of FZK gml file:
![image](https://github.com/3dcitydb/citydb-tool/assets/42941872/14e93f66-fb3e-41e8-b17d-9fc00a185095)

- Steps to Reproduce
1. Download the TUM CityGML 3.0 Transportation dataset.
2. Import the TUM_citygml_V3.gml file using citydb-tool v. 0.7.1-beta.
3. Check the feature and geometry_data tables in PostgreSQL for missing envelopes and geometries.
4. Download the FZK Haus CityGML 3.0 test dataset.
5. Import the FZK dataset and observe the presence of envelopes and geometries.

- Environment
- Citydb-tool version: 0.7.1-beta
- Database: PostgreSQL
- Operating System: MacOS Ventura 13.6.7

I appreciate any insights or suggestions on resolving this issue in advance. Thank you.

**Comment by clausnagel** [comment] 2024-06-26 16:53
The TUM dataset violates the CityGML conceptual model. That's why it's not fully imported by citydb-tool.

The issue is not the geometry. `gml:Surface`, `gml:patches`, and `gml:PolygonPatch` are all supported by citydb-tool.

The problem is caused by the `core:boundary` elements which link `tran:TrafficArea` and `tran:AuxiliaryTrafficArea` boundaries to `tran:Section` spaces. According to the CityGML 3.0 conceptual model standard, both boundary types are not allowed for sections (see [here](https://docs.ogc.org/is/20-010/20-010.html#transportation-boundaries-table)).

You can manually fix the dataset by replacing
```xml
<tran:Section>
  <core:boundary>
    <tran:TrafficArea>
      ...
    </tran:TrafficArea>
  </core:boundary>
<tran:Section>
```

with
```xml
<tran:Section>
  <tran:trafficSpace>
    <tran:TrafficSpace>
      <core:boundary>
        <tran:TrafficArea>
          ...
        </tran:TrafficArea>
      </core:boundary>
    </tran:TrafficSpace>
  </tran:trafficSpace>
<tran:Section>
```

Be careful to use `tran:auxiliaryTrafficSpace` and `tran:AuxiliaryTrafficSpace` instead to enclose the `tran:AuxiliaryTrafficArea` boundaries in the dataset.

**Comment by ChBeil** [comment] 2024-06-27 07:23
Thanks for pointing this out. We fixed the issue and updated the dataset.

**Comment by bsttsai** [comment] 2024-06-27 10:52
@clausnagel Thanks for the explanations and solutions. 
@ChBeil Thanks for updating the TUM dataset! now it works normally with the citydb-tool. Could you please also update the "CityGML3_Transportation_NYC" dataset in the same repository? as it has the same missing (auxiliary) traffic space issue to link with `tran:Section` spaces.

**Comment by clausnagel** [comment] 2024-06-27 19:42
Closing this isssue. Disucssion about fixing other datasets should take place in the TUM repository.

**Closed by clausnagel** 2024-06-27 19:42 UTC
Labels: question
